source/portfolio/urls.py
from django.urls import path
from . import views
app_name = 'portfolio'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

source/setupfiles/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("portfolio.urls", namespace="portfolio")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

source/portfolio/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.CharField(max_length=300)

    def __str__(self):
        return self.name + " " + self.message[:20]

source/portfolio/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Your Name"}))

    email = forms.CharField(
        widget=forms.EmailInput(attrs={"placeholder": "Your Email Address"})
    )

    message = forms.CharField(
        widget=forms.Textarea(attrs={"placeholder": "Message", "rows": 4})
    )

    class Meta:
        model = Contact
        fields = "__all__"

source/portfolio/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import TemplateView, CreateView
from django.contrib import messages
from .models import Contact
from .forms import ContactForm
from django.forms import BaseModelForm


class HomeView(TemplateView):
    template_name = "portfolio/index.html"


class AboutView(TemplateView):
    template_name = "portfolio/about.html"


class ContactView(CreateView):
    model = Contact
    template_name = "portfolio/contact.html"
    form_class = ContactForm
    success_url = "/contact/"

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        form.save()
        messages.success(
            self.request,
            "Thank You for submitting you query.<br>We will get in touch with you soon!!",
        )
        return super().form_valid(form)

source/templates/portfolio/about.html
{% extends 'portfolio/base.html' %}
{% load static %}

{% block title %}
Portfolio | About
{% endblock title %}

{% block stylesheet %}
<link href="{% static 'portfolio/css/style.css' %}" rel="stylesheet">
{% endblock stylesheet %}

{% block header-content %}
{% include 'portfolio/navbar.html' %}
<div class="view intro" style="background: url('/static/portfolio/images/pagebar.jpg') no-repeat center center;">
    <div class="full-bg-img">
        <div class="mask flex-center">
            <div class="page-head-container col-md-6 text-right pr-5 white-text wow zoomIn slow">
                <h2 class="page-header">About Myself</h2>
                <div class="page-container ml-auto">
                    <small>Home</small>
                    <small>About</small>
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock header-content %}



{% block main-content %}
<section class="work-area" style="background: url('/static/portfolio/images/intro.jpg') no-repeat center center;">
    <div class="container-fluid align-middle">
        <div class="row">
            <div class="view overlay zoom col-md-4 offset-md-1 align-middle">
                <img src="{% static 'portfolio/images/dp.jpg' %}" class="img-fluid rounded-circle" alt="zoom">
            </div>
            <div class="col-md-5 ml-md-2 align-middle wow zoomIn">
                <h2>Introduction</h2>
                <hr class="hr-light">
                <p class="mt-md-4" align="justify">IT Professional with 14+ years of experience in Application
                    Development. Started my career as a Mainframe COBOL developer, but got sucked into the realm of web
                    development
                    after developing an interest in Python-Django. Still learning the many intricacies of HTML, CSS,
                    JavaScript.
                    I have experience in multiple financial domains like Capital Markets, Investment Banking (Wealth
                    Management)
                    and Retail Banking.
                </p>
                <p>My ultimate aim with this exercise is to convert my learning into experience with a prestigious firm.
                </p>
                <hr class="text-dark">
                <div class="contact">
                    <h5>CONTACT DETAILS</h5>
                    <hr class="hr-light">
                    <p class="mt-2"><strong>Name:</strong> Praveen Phatak</p>
                    <p class="mt-0 pt-0"><strong>Current City:</strong> Pune, India</p>
                    <p class="mt-0 pt-0"><strong>Phone:</strong> 9130469142</p>
                    <p class="mt-0 pt-0"><strong>Email:</strong> praveenphatak@gmail.com</p>
                </div>

            </div>
        </div>
    </div>
</section>

<section class="skills-area">
    <div class="container m-auto">
        <div class="row d-flex flex-center mb-5">
            <h2>Skills to Offer</h2>
        </div>
        <div class="row d-flex flex-center">
            <div class="col-md-3 skill-col">
                <div class="item-wrapper wow slideInLeft">
                    <div class="item d-flex">
                        <div class="item-icon">
                            <i class="fas fa-city"></i>

                        </div>
                        <div class="item-title d-flex flex-column">
                            <h3>MAINFRAME DEVELOPMENT</h3>
                            <small>COBOL, JCL, CICS, VSAM</small>
                           
                        </div>
                    </div>
                </div>

                <div class="item-wrapper wow slideInLeft slow">
                    <div class="item d-flex">
                        <div class="item-icon">
                            <i class="fas fa-cogs"></i>
                        </div>
                        <div class="item-title d-flex flex-column">
                            <h3>PROGRAMMING LANGUAGES</h3>
                            <small>Python</small>
                        </div>
                    </div>
                </div>

                <div class="item-wrapper wow slideInLeft slower">
                    <div class="item d-flex">
                        <div class="item-icon">
                            <i class="fas fa-database"></i>
                        </div>
                        <div class="item-title d-flex flex-column">
                            <h3>DATABASES</h3>
                            <small>IBM-DB2, SQLite, MySQL</small>
                       
                        </div>
                    </div>
                </div>

                <div class="item-wrapper wow slideInLeft slower delay-1s">
                    <div class="item d-flex">
                        <div class="item-icon">
                            <i class="far fa-chart-bar"></i>
                        </div>
                        <div class="item-title">
                            <h3>ANALYTICAL</h3>
                            <small>Business Analysis, Agile Scrum</small>
                        </div>
                    </div>
                </div>


            </div>

            <div class="skill-img col-md-5 wow fadeInUp">
                <img src="{% static 'portfolio/images/skills.png' %}" class="img-fluid" alt="">
            </div>

            <div class="col-md-3 align-middle">
                <div class="item-wrapper wow slideInRight">
                    <div class="item d-flex">
                        <div class="item-icon">
                            <i class="fas fa-tv"></i>
                        </div>
                        <div class="item-title d-flex flex-column">
                            <h3>WEB DEVELOPMENT</h3>
                            <small>HTML5, CCS3, JavaScript</small>
                        </div>
                    </div>
                </div>

                <div class="item-wrapper wow slideInRight slow">
                    <div class="item d-flex">
                        <div class="item-icon">
                            <i class="fas fa-globe"></i>
                        </div>
                        <div class="item-title d-flex flex-column">
                            <h3>WEB FRAMEWORK</h3>
                            <small>Django</small>

                        </div>
                    </div>

                    <div class="item-wrapper wow slideInRight slower">
                        <div class="item d-flex">
                            <div class="item-icon">
                                <i class="fab fa-keycdn"></i>
                            </div>
                            <div class="item-title d-flex flex-column">
                                <h3>PRODUCTS</h3>
                                <small>MQ-Series, Denodo, Tableau</small>
                            </div>
                        </div>
                    </div>


                    <div class="item-wrapper wow slideInRight slower delay-1s">
                        <div class="item d-flex">
                            <div class="item-icon">
                                <i class="fas fa-award"></i>
                            </div>
                            <div class="item-title">
                                <h3>CERTIFICATIONS</h3>
                                <small>IBM DB2 Certified Associate, PSM-1, MTA Python Certified</small>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
</section>

<section class="project-area" style="background: url('/static/portfolio/images/timeline.jpg') no-repeat center center;">
    <div class="container m-auto">
        <div class="row d-flex flex-center mb-5">
            <h2>Career Timeline</h2>
        </div>
        <div class="timeline m-auto">
            <div class="time-container left wow zoomIn slow">
                <div class="content peach-gradient">
                    <h5>UBS Business Solutions India</h5>
                    <hr>
                    <blockquote>
                        <h6>Designation: <small>Authorized Officer</small></h6>
                        <small>Dec-2017 to Present</small </blockquote> <ul class="mt-3">
                        <li><small>Involved in Legacy Modernization Initatives (WMAP) and
                                implementing automation scripts.</small>
                        </li>
                        </ul>

                </div>
            </div>
            <div class="time-container right wow zoomIn slow delay-1s">
                <div class="content peach-gradient">
                    <h5>HSBC Technology India</h5>
                    <hr>
                    <blockquote>
                        <h6>Designation: <small>Consultant Specialist</small></h6>
                        <small>Oct-2016 to Dec 2017</small>
                    </blockquote>
                    <ul class="mt-3">
                        <li><small>Involved in firmwide initiative of consolidation and
                                integration of segregated banking applications into centralized
                                HSBC platform.</small></li>
                    </ul>
                </div>
            </div>
            <div class="time-container left wow zoomIn slow delay-2s">
                <div class="content peach-gradient">
                    <h5>Tata Consultancy Services</h5>
                    <hr>
                    <blockquote>
                        <h6>Designation: <small>Assistant Consultant</small></h6>
                        <small>Sep-2006 to Oct-2016</small>
                    </blockquote>
                    <ul class="mt-3">
                        <li><small>Worked as Consultant for Morgan Stanley, leading and managing several
                                change requests like Wire Transfer Automation, Same day ACH, Remote Check Deposit
                                and Dodd Frank Act regulation.
                            </small></li>
                        <br>
                        <li><small>Worked on various technology initiatives like VSAM to DB2 migration &
                                Performance Optimization of EOD batch cycle.
                            </small></li>
                    </ul>
                </div>
            </div>


        </div>
    </div>

</section>

{% endblock main-content %}

source/templates/portfolio/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>
        {% block title %}

        {% endblock title %}
    </title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/mdbootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'vendor/mdbootstrap/css/mdb.min.css' %}" rel="stylesheet">

    <!-- Your custom styles (optional) -->
    {% block stylesheet %}

    {% endblock stylesheet %}


</head>

<body>

    <header>
        {% block header-content %}

        {% endblock header-content %}

    </header>


    <main>
        {% block main-content %}

        {% endblock main-content %}

    </main>


    {% include 'portfolio/footer.html' %}


    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'vendor/mdbootstrap/js/jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'vendor/mdbootstrap/js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'vendor/mdbootstrap/js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'vendor/mdbootstrap/js/mdb.min.js' %}"></script>
    <!-- Bootstrap Animation JavaScript -->
    <script type="text/javascript" src="{% static 'vendor/mdbootstrap/js/modules/wow.js' %}"></script>
    <!-- Custom JavaScript -->
    <script type="text/javascript" src="{% static 'portfolio/js/app.js' %}"></script>
</body>

</html>

source/templates/portfolio/contact.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Portfolio | Contact
{% endblock title %}

{% block stylesheet %}
<link href="{% static 'portfolio/css/style.css' %}" rel="stylesheet">
{% endblock stylesheet %}

{% block header-content %}
{% include 'portfolio/navbar.html' %}
<div class="view intro" style="background: url('/static/portfolio/images/pagebar.jpg') no-repeat center center;">
    <div class="full-bg-img">
        <div class="mask flex-center">
            <div class="page-head-container col-md-6 text-right pr-5 white-text wow zoomIn slow">
                <h2 class="page-header">Contact Me</h2>
                <div class="page-container ml-auto">
                    <small>Home</small>
                    <small>Contact</small>
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock header-content %}



{% block main-content %}
<section class="contact-area" style="background: url('/static/portfolio/images/timeline.jpg') no-repeat center center;">
    <div class="container m-auto">
        <div class="row d-flex flex-center flex-column mb-5">
            <h2>Get in Touch</h2>
            <img src="{% static 'portfolio/images/img-01.png' %}" class="img-fluid" alt="">
        </div>

        <div class="row">
            <div class="contact-info col-md-5 mt-5">
                <div class="item-wrapper mb-4 pt-5">
                    <div class="item d-flex">
                        <div class="item-icon">
                            <i class="fas fa-home"></i>
                        </div>
                        <div class="item-title mt-0 ml-3">
                            <p>Pune, India</p>
                            <small class="pt-0">Kharadi</small>
                        </div>
                    </div>
                </div>

                <div class="item-wrapper mb-4">
                    <div class="item d-flex">
                        <div class="item-icon">
                            <i class="fas fa-phone"></i>
                        </div>
                        <div class="item-title mt-0 ml-3">
                            <p>+91 9130-469-142</p>
                            <small class="pt-0">Mon to Fri- 9:00 AM to 6:00 PM</small>
                        </div>
                    </div>
                </div>

                <div class="item-wrapper mb-4">
                    <div class="item d-flex">
                        <div class="item-icon">
                            <i class="far fa-envelope"></i>
                        </div>
                        <div class="item-title mt-0 ml-3">
                            <p>praveenphatak@gmail.com</p>
                            <small class="pt-0">Send us the query anytime soon!</small>
                        </div>
                    </div>
                </div>
            </div>


            <div class="col-md-6">
                <!-- Material form login -->

                {% if messages %}
                <div class="jumbotron text-center my-5">
                    <ul class="messages">
                        {% for message in messages %}
                        <li {% if message.tags %} class="{{message.tags}}" {% endif %}>{{message|safe}}</li>
                        {% endfor %}
                    </ul>
                </div>

                {% else %}
                <div class="card animated wow zoomIn data-wow-delay='0.4s'">
                    <h5 class="card-header text-center py-3">
                        <strong>Would like to hear from you!</strong>
                    </h5>
                    <!--Card content-->
                    <div class="card-body px-lg-5">
                        <!-- Form -->
                        <form method="POST" style="color: #757575;">
                            {% csrf_token %}
                            {{form|crispy}}
                            <!-- Sign in button -->
                            <input type="hidden" name="next" value="{{ next }}" />
                            <button class="btn purple-gradient mt-5" type="submit">Connect</button>

                        </form>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>

    </div>
</section>


{% endblock main-content %}

source/templates/portfolio/footer.html
{% load static %}
<footer style="background: url('/static/portfolio/images/header-back.jpg') no-repeat center center;">
    <div class="container-fluid">

        <div class="d-flex flex-column justify-content-center align-items-center">
            <div class="mt-5">
                <i class="fab fa-python fa-2x"></i>
            </div>
            <div class="mt-2">
                <p>A Website developed with Python-Django framework</p>
            </div>
            <div class="mt-2">
                <a class="footer-link" href=""><i class="fab fa-facebook prefix mr-3"></i></a>
                <a class="footer-link" href=""><i class="fab fa-instagram prefix mr-3"></i></a>
                <a class="footer-link" href=""><i class="fab fa-linkedin prefix mr-3"></i></a>
                <a class="footer-link" href=""><i class="fab fa-github prefix mr-3"></i></a>
            </div>
            <div class="my-5">
                <small class="white-text">Copyright &copy 2020 reserved | This template is made with 
                    <i class="far fa-heart"></i> by Praveen-Phatak</small>
            </div>

        </div>


    </div>
</footer>

source/templates/portfolio/index.html
{% extends 'portfolio/base.html' %}
{% load static %}


{% block title %}
Portfolio | Home
{% endblock title %}


{% block stylesheet %}
<link href="{% static 'portfolio/css/style.css' %}" rel="stylesheet">
{% endblock stylesheet %}


{% block header-content %}
{% include 'portfolio/navbar.html' %}
<div class="view intro-2" style="background: url('/static/portfolio/images/back2.jpg');">
    <div class="full-bg-img">
        <div class="mask d-flex flex-center justify-content-center ml-auto">
            <div class="text-center white-text wow fadeInUp">
                <h1 id="name">Praveen Phatak</h1>
                <h5 id="website" class="mt-5">Personal Portfolio Website</h5>

            </div>
        </div>
        <!-- <i class="fas fa-angle-double-down fa-2x"></i> -->
    </div>
    <a class="purple-gradient" href="">
        <span class="vertical-line"></span>
        <i class="fas fa-angle-double-down fa-2x"></i>
    </a>
</div>

{% endblock header-content %}


{% block main-content %}
<section class="work-area" style="background: url('/static/portfolio/images/intro.jpg') no-repeat center center;">
    <div class="container-fluid align-middle">
        <div class="row">
            <div class="view overlay zoom col-md-4 offset-md-1 align-middle">
                <img src="{% static 'portfolio/images/dp.jpg' %}" class="img-fluid rounded-circle" alt="zoom">
            </div>
            <div class="col-md-5 ml-md-2 align-middle">
                <h2>About Myself</h2>
                <hr class="hr-light">
                <p class="mt-md-4" align="justify">IT Professional with 14+ years of experience in Application
                    Development. Started my career as a Mainframe COBOL developer, but got sucked into the realm of web
                    development
                    after developing an interest in Python-Django.
                </p>

                <a class="btn purple-gradient btn-rounded" href="{% url 'portfolio:about' %}">More Info</a>
            </div>
        </div>
    </div>
</section>


{% endblock main-content %}

source/templates/portfolio/navbar.html
{% load static %}

<div class="container">
    <nav class="navbar fixed-top navbar-expand-lg scrolling-navbar">
        <a class="navbar-brand" href="{% url 'portfolio:home' %}"><strong>Praveen Portfolio</strong></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="white-text">
                <i class="fas fa-bars"></i>
            </span>
        </button>
        <!-- <div class="nav-container"> -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'portfolio:home' %}">Home <span
                            class="sr-only">(current)</span></a>
                </li>
                <!-- <li class="nav-item dropdown multi-level-dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">Portfolio
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownPortfolio">
                            <a class="dropdown-item" href="#">Games</a>
                            <a class="dropdown-item" href="#">Projects</a>
                            <a class="dropdown-item" href="#">Other</a>
                        </div>
                    </li> -->
                <li class="nav-item dropdown multi-level-dropdown">
                    <a href="#" id="menu" data-toggle="dropdown" class="nav-link dropdown-toggle w-100">Portfolio</a>
                    <ul class="dropdown-menu mt-2 rounded-0 border-0 z-depth-1">
                        <li class="dropdown-item dropdown-submenu p-0">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle text-warning">Games</a>
                            <ul class="dropdown-menu ml-2 rounded-0 dark-color border-0 z-depth-1">
                                <li class="dropdown-item p-0">
                                    <a href="#" class="text-warning w-100">Bingo</a>
                                </li>
                                <li class="dropdown-item p-0">
                                    <a href="#" class="text-warning w-100">QuizMaster</a>
                                </li>
                                <li class="dropdown-item dropdown-submenu p-0">
                                    <a href="#" data-toggle="dropdown" class="dropdown-toggle text-warning w-100">Hello
                                    </a>
                                    <ul class="dropdown-menu mr-2 rounded-0 dark-color border-0 z-depth-1 r-100 ">
                                        <li class="dropdown-item p-0">
                                            <a href="#" class="text-warning w-100">Some</a>
                                        </li>
                                        <li class="dropdown-item p-0">
                                            <a href="#" class="text-warning w-100">Text</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown-item dropdown-submenu">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle text-warning">Projects</a>
                            <ul class="dropdown-menu mr-2 rounded-0 dark-color border-0 z-depth-1 r-100 ">
                                <li class="dropdown-item p-0">
                                    <a href="#" class="text-warning w-100">IPL</a>
                                </li>
                                <li class="dropdown-item p-0">
                                    <a href="#" class="text-warning w-100">are</a>
                                </li>
                                <li class="dropdown-item p-0">
                                    <a href="#" class="text-warning w-100">you </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'portfolio:about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'portfolio:contact' %}">Contact</a>
                </li>
            </ul>
        </div>
        <!-- </div> -->
    </nav>
</div>